#!/bin/python

import sys
from pprint import pprint
import parse
import check

path = sys.argv[1]

with open(path, "r") as f:
    src = f.read()

ast = parse.parse(src)

c = check.Check(path, src)
c.check_file(ast)
